apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: apps/
    repoURL: https://github.com/viktor-kurchenko/argocd.git
    targetRevision: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
